security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider: 
            chain:
                providers: [fos_userbundle, my_ldap]
        fos_userbundle:
            id: fos_user.user_provider.username_email
        my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: dc=orange-sonatel,dc=com
                search_dn: "cn=read-only-admin,dc=orange-sonatel,dc=com"
                search_password: password
                default_roles: ROLE_USER
                uid_key: sAMAccountName
                extra_fields: ['email']
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: chain_provider
            json_login:
                check_path: fos_user_security_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        reinitialisationMotDePass:
            pattern:  ^/reinitialisationMotDePass
            stateless: true
            anonymous: true
            provider: fos_userbundle
        app_reset_password:
            pattern: ^/reset
            stateless: true
            anonymous: true
        app_check_email:
            pattern: ^/check-email
            stateless: true
            anonymous: true
        test:
            pattern: ^/test
            stateless: true
            anonymous: true
        main:
            pattern:   ^/*
            stateless: true
            provider: chain_provider

            logout:
                path: deconnexion
            
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reinitialisationMotDePass, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/check-email, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/test, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api, roles : IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN}
       
        
