<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbC8RDn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbC8RDn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXbC8RDn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXbC8RDn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXbC8RDn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XbC8RDn',
    'container.build_id' => 'a43b516f',
    'container.build_time' => 1640794440,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXbC8RDn');
