<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVfQCG8Q\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVfQCG8Q/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVfQCG8Q.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVfQCG8Q\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVfQCG8Q\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VfQCG8Q',
    'container.build_id' => '43ee3a24',
    'container.build_time' => 1642761408,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVfQCG8Q');
