<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFL7xxTM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFL7xxTM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFL7xxTM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFL7xxTM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFL7xxTM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FL7xxTM',
    'container.build_id' => '7fd75e50',
    'container.build_time' => 1644486561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFL7xxTM');
